export enum TransactionEnum {
  PENDING = "PENDING",
  ERROR = "ERROR",
  SUCCESS = "SUCCESS",
}

export enum ErrorTypeEnum {
  AUTH = "AUTH",
  ROLE = "ROLE",
  AUDIT_STATE = "AUDIT_STATE",
  VALIDATION = "VALIDATION",
  BLOB = "BLOB",
  OTHER = "OTHER",
}

export enum AuditStateEnum {
  CAN_MANAGE_REQUESTS = "CAN_MANAGE_REQUESTS",
  CAN_LOCK_AUDIT = "CAN_LOCK_AUDIT",
  CAN_REMOVE_VERIFICATION = "CAN_REMOVE_VERIFICATION",
  CAN_REMOVE_REQUEST = "CAN_REMOVE_REQUEST",
  IS_REJECTED = "IS_REJECTED",
  CAN_ADD_REQUEST = "CAN_ADD_REQUEST",
  CAN_FINALIZE = "CAN_FINALIZE",
  CAN_SUBMIT_FINDINGS = "CAN_SUBMIT_FINDINGS",
  CAN_UNLOCK = "CAN_UNLOCK",
  CAN_ATTEST = "CAN_ATTEST",
}

export enum ActionEnum {
  AUDITOR_TERMS_APPROVED = "AUDITOR_TERMS_APPROVED",
  AUDITOR_TERMS_REJECTED = "AUDITOR_TERMS_REJECTED",
  AUDITOR_FINDINGS = "AUDITOR_FINDINGS",
  AUDITOR_LEFT = "AUDITOR_LEFT",
  OWNER_APPROVED = "OWNER_APPROVED",
  OWNER_LOCKED = "OWNER_LOCKED",
  OWNER_OPENED = "OWNER_OPENED",
  OWNER_EDITED = "OWNER_EDITED",
  OWNER_FINALIZED = "OWNER_FINALIZED",
  OWNER_REVEALED = "OWNER_REVEALED",
}

export enum AuditStatusEnum {
  DISCOVERY = "DISCOVERY",
  ATTESTATION = "ATTESTATION",
  AUDITING = "AUDITING",
  CHALLENGEABLE = "CHALLENGEABLE",
  FINALIZED = "FINALIZED",
}

export enum MembershipStatusEnum {
  VERIFIED = "VERIFIED",
  REQUESTED = "REQUESTED",
  REJECTED = "REJECTED",
}

export enum RoleTypeEnum {
  OWNER = "OWNER",
  AUDITOR = "AUDITOR",
}
