export enum TransactionEnum {
  PENDING = "PENDING",
  ERROR = "ERROR",
  SUCCESS = "SUCCESS",
}

export enum ErrorTypeEnum {
  AUTH = "AUTH",
  ROLE = "ROLE",
  AUDIT_STATE = "AUDIT_STATE",
  VALIDATION = "VALIDATION",
  BLOB = "BLOB",
  OTHER = "OTHER",
}

export enum AuditStateEnum {
  CAN_MANAGE_REQUESTS = "CAN_MANAGE_REQUESTS",
  CAN_LOCK_AUDIT = "CAN_LOCK_AUDIT",
  CAN_REMOVE_VERIFICATION = "CAN_REMOVE_VERIFICATION",
  CAN_REMOVE_REQUEST = "CAN_REMOVE_REQUEST",
  IS_REJECTED = "IS_REJECTED",
  CAN_ADD_REQUEST = "CAN_ADD_REQUEST",
  CAN_FINALIZE = "CAN_FINALIZE",
  CAN_SUBMIT_FINDINGS = "CAN_SUBMIT_FINDINGS",
  CAN_UNLOCK = "CAN_UNLOCK",
  CAN_ATTEST = "CAN_ATTEST",
}
