name: Build and Test

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

jobs:
  setup-and-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v4
        with:
          project_id: billowing-feather-81805198
          parent: dev/pete # optional (defaults to your primary branch)
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch-name.outputs.current_branch }}
          username: bevor
          database: bevor
          api_key: ${{ env.NEON_API_KEY }}

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install npm dependencies
      - name: Install dependencies
        run: yarn install

      - uses: dopplerhq/cli-action@v3

      # Build the application
      - name: Build
        run: yarn build
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}?sslmode=require

      - name: Deploy DB
        run: |
          echo ${{ steps.create-branch.outputs.host }}
          echo ${{ steps.create-branch.outputs.branch_id }}
          echo ${{ steps.create-branch.outputs.db_url }}?sslmode=require
          yarn drizzle-kit migrate
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}?sslmode=require

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          message: |
            Neon branch :elephant: : https://console.neon.tech/app/projects/billowing-feather-81805198/branches/${{ steps.create-branch.outputs.branch_id }}

      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          browser: chrome
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}?sslmode=require
