name: Cypress Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-and-build:
    runs-on: ubuntu-22.04
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      # Install npm dependencies
      - name: Install dependencies
        run: yarn install

      # Generate Prisma Client to reflect latest database schema
      - name: Generate Prisma Client
        run: doppler run -- yarn prisma generate

      # Build the application
      - name: Build
        run: yarn build

  migration:
    runs-on: ubuntu-22.04
    needs: setup-and-build
    steps:
      - name: Deploy DB changes
        run: doppler run -- yarn prisma migrate deploy

  cypress-run:
    runs-on: ubuntu-22.04
    needs: migration
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          browser: chrome
          wait-on: "http://localhost:3000"
