name: Cypress Tests

on:
  workflow_run:
    workflows: ["Build + Migrate"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: actions/cache@v3
        with:
          path: ~/.doppler
          key: ${{ runner.os }}-doppler-${{ hashFiles('**/doppler.lock') }}
          restore-keys: |
            ${{ runner.os }}-doppler-

      - name: Install Doppler CLI
        if: steps.cache.outputs.cache-hit != 'true'
        uses: dopplerhq/cli-action@v1

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          browser: chrome
          wait-on: "http://localhost:3000"
